# Generated by Django 4.1.4 on 2023-04-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_table_l'),
    ]

    operations = [
        migrations.CreateModel(
            name='table_t',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Timestamp', models.DateTimeField()),
                ('Products', models.CharField(max_length=20)),
                ('From_L', models.CharField(max_length=20)),
                ('To_L', models.CharField(max_length=20)),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
